# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Fishing")
        Form.resize(500, 500)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        self.ChooseRegion = QtWidgets.QPushButton(Form)
        self.ChooseRegion.setGeometry(QtCore.QRect(100, 450, 100, 40))
        self.ChooseRegion.setObjectName("ChooseRegion")
        self.Region = QtWidgets.QLabel(Form)
        self.Region.setGeometry(QtCore.QRect(50, 50, 400, 400))
        self.Region.setObjectName("Region")
        self.FishingButtom = QtWidgets.QPushButton(Form)
        self.FishingButtom.setGeometry(QtCore.QRect(300, 450, 100, 40))
        self.FishingButtom.setObjectName("FishingButtom")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ChooseRegion.setText(_translate("Form", "选择区域"))
        self.Region.setText(_translate("Form", "TextLabel"))
        self.FishingButtom.setText(_translate("Form", "开始钓鱼"))
